services:
  db:
    restart: unless-stopped
  redis:
    restart: unless-stopped
  web:
    restart: unless-stopped
  worker-small:
    restart: unless-stopped
  worker-big:
    restart: unless-stopped
  caddy:
    restart: unless-stopped
