logging:
  receivers:
    docker_json:
      type: files
      include_paths:
        - /var/lib/docker/containers/*/*.log
        - /srv/lean-report-card/docker/containers/*/*.log
  processors:
    parse_json:
      type: parse_json
  service:
    pipelines:
      docker:
        receivers: [docker_json]
        processors: [parse_json]

metrics:
  receivers:
    hostmetrics:
      type: hostmetrics
      collection_interval: 60s
    lrc_prometheus:
      type: prometheus
      config:
        scrape_configs:
          - job_name: lean-report-card
            scrape_interval: 30s
            static_configs:
              - targets: ["127.0.0.1:8000"]
  service:
    pipelines:
      host:
        receivers: [hostmetrics]
      app:
        receivers: [lrc_prometheus]
